# Yang wajib diisi
# 1. nama worker (ubah juga di Cargo.toml)
# 2. account id cloudflare
# 3. KV Storage
# 4. id KV Storage tadi
# 5. UUID

# ===============[ nama worker ]=================
name = "dikuotainaja"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

# ===============[ account id ]==================
account_id = "487b5e794560518a4a9880cfafa1dd22"
workers_dev = true

# ===============[ KV STORAGE ]==================
[[kv_namespaces]]
binding = "AIO"
id = "4b2249c348ac45b5a3b83ac83f5a8ddd"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

# =================[ UUID V4 ]===================
[vars]
UUID = "5c3c299d-20ac-40ea-a68d-62128020c92d"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/invesibletint/teknik/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/invesibletint/teknik/refs/heads/main/web/sub.html"

# ------- Dimodifikasi oleh: @vpnjatimbot -------
